### PR TITLE
chore(deps): update node & ESLint versions

### PR DESCRIPTION
**Pull request by tehhowch**
- Update workflows to use the latest Node LTS, 16
 - Update the ESLint version to latest minor

### CODE REVIEW

**Comment by tehhowch** [comment]
@AardWolf @DevJackSmith bump

**Comment by AardWolf** [comment]
Sorry gang. I'm now aware of this but how do we plan to move it forward? Merge, pull on server, upgrade necessaries, restart? I am not sure where node is being used in the extension - feels like a server thing?

**Comment by tehhowch** [comment]
> Sorry gang. I'm now aware of this but how do we plan to move it forward? Merge, pull on server, upgrade necessaries, restart? I am not sure where node is being used in the extension - feels like a server thing?

NodeJS is basically the runtime environment that all JavaScript in the GitHub workflow will execute in. The extension itself doesn't use NodeJS, it runs in the browser's JavaScript environment (e.g. V8, JavaScriptCore, Chakra, SpiderMonkey).

So there's no server changes needed IMO.

**Comment by DevJackSmith** [comment]
just noticed this. thanks for the pr. This indeed runs only on github servers, since this is a github action.

**Comment by DevJackSmith** [comment]
the package on the other hand is on the server. And i think it's something like npm install that installs correct versions of things

**Comment by DevJackSmith** [comment]
I think we do have node on the server, but it's not getting upgraded here.

**Pull request merged**
